// {
//     "name": "dashv2.sprie.io",
//     "version": "0.2.2007",
//     "private": true,
//     "engines": {
//       "npm": "please-use-yarn",
//       "yarn": ">=1.17.3",
//       "node": ">=16.0.0"
//     },
//     "scripts": {
//       "dev": "vite",
//       "build": "tsc && vite build",
//       "preview": "vite preview",
//       "pre-commit-lint": "tsc && yarn lint-staged",
//       "lint": "eslint --fix \"./src/**/*.{ts,tsx}\"",
//       "format": "prettier --ignore-path .gitignore --write \"**/*.+(js|ts|tsx|json)\"",
//       "prepare": "husky install",
//       "test:watch": "vitest",
//       "test:cov": "vitest run --coverage",
//       "test": "cross-env DEV_CI=1 vitest",
//       "test:e2e": "cross-env DEV_CI=1 playwright test",
//       "test:e2e-ui": "cross-env DEV_CI=1 playwright test --ui"
//     },
//     "dependencies": {
//       "@coreui/chartjs": "^3.0.0",
//       "@coreui/coreui-pro": "^4.3.2",
//       "@coreui/icons": "^2.1.0",
//       "@coreui/icons-react": "^2.1.0",
//       "@coreui/react-chartjs": "^2.1.0",
//       "@coreui/react-pro": "^4.4.0",
//       "@coreui/utils": "^1.3.1",
//       "@perceptimagery/sprie-face-sdk": "^1.2.1037",
//       "axios": "^1.3.4",
//       "chart.js": "^3.8.0",
//       "classnames": "^2.3.1",
//       "core-js": "^3.23.5",
//       "eslint-plugin-testing-library": "^5.10.3",
//       "localforage": "^1.10.0",
//       "react": "^18.2.0",
//       "react-app-polyfill": "^3.0.0",
//       "react-dom": "^18.2.0",
//       "react-icons": "^4.7.1",
//       "react-qr-code": "^2.0.11",
//       "react-router-dom": "^6.8.0",
//       "short-uuid": "^4.2.2",
//       "simplebar": "^6.2.0",
//       "simplebar-react": "^2.4.1",
//       "swr": "^2.0.3",
//       "web-vitals": "^3.1.1"
//     },
//     "devDependencies": {
//       "@playwright/test": "^1.33.0",
//       "@testing-library/jest-dom": "^5.16.5",
//       "@testing-library/react": "^14.0.0",
//       "@testing-library/react-hooks": "^8.0.1",
//       "@types/is-ci": "^3.0.0",
//       "@types/json-schema": "^7.0.11",
//       "@types/node": "^18.11.18",
//       "@types/react": "^18.0.26",
//       "@types/react-dom": "^18.0.9",
//       "@types/trusted-types": "^2.0.2",
//       "@typescript-eslint/eslint-plugin": "^5.48.2",
//       "@typescript-eslint/parser": "^5.48.2",
//       "@vitejs/plugin-react": "^3.0.0",
//       "@vitest/coverage-c8": "^0.31.0",
//       "cross-env": "^7.0.3",
//       "eslint": "^8.32.0",
//       "eslint-config-airbnb": "^19.0.4",
//       "eslint-config-airbnb-typescript": "^17.0.0",
//       "eslint-config-prettier": "^8.8.0",
//       "eslint-import-resolver-alias": "^1.1.2",
//       "eslint-import-resolver-typescript": "^3.5.3",
//       "eslint-plugin-import": "^2.27.5",
//       "eslint-plugin-jsx-a11y": "^6.7.1",
//       "eslint-plugin-prettier": "^4.2.1",
//       "eslint-plugin-react": "^7.32.1",
//       "eslint-plugin-react-hooks": "^4.6.0",
//       "eslint-plugin-security": "^1.7.1",
//       "eslint-plugin-vitest": "^0.1.5",
//       "husky": "^8.0.3",
//       "is-ci": "^3.0.1",
//       "jsdom": "^22.0.0",
//       "lint-staged": "^13.2.2",
//       "prettier": "^2.8.8",
//       "sass": "^1.58.0",
//       "typescript": "^4.9.3",
//       "vite": "^4.0.0",
//       "vite-plugin-mkcert": "^1.12.0",
//       "vite-tsconfig-paths": "^4.2.0",
//       "vitest": "^0.31.0"
//     }
//   }
